"""empty message

Revision ID: 4e3ccf43fb31
Revises: 
Create Date: 2024-03-08 18:47:58.038905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e3ccf43fb31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('contato', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('pecas',
    sa.Column('id_peca', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('km', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id_peca')
    )
    op.create_table('cliente_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_veiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculo.id_veiculo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo_pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_peca', sa.Integer(), nullable=True),
    sa.Column('id_veiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_peca'], ['pecas.id_peca'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculo.id_veiculo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('km', sa.Numeric(), nullable=True))
        batch_op.alter_column('cor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('placa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('marca',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('ano',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               nullable=True)
        batch_op.alter_column('modelo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('km_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('km_2', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('modelo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('ano',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('marca',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('placa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('km')

    op.drop_table('veiculo_pecas')
    op.drop_table('cliente_veiculo')
    op.drop_table('pecas')
    op.drop_table('cliente')
    # ### end Alembic commands ###
