"""empty message

Revision ID: 81da8168f326
Revises: 
Create Date: 2024-03-03 01:01:17.462287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81da8168f326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('nome', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('idade', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('sexo', mysql.CHAR(length=1), nullable=True),
    sa.Column('peso', mysql.FLOAT(), nullable=True),
    sa.Column('altura', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('post')
    # ### end Alembic commands ###
